version: '3.4'

services:
  amazingco.apigw:
    image: ${DOCKER_REGISTRY-}amazingcoapigw
    build:
      context: .
      dockerfile: AmazingCo.ApiGW/Dockerfile
    depends_on:
      - amazingco

  amazingco:
    image: ${DOCKER_REGISTRY-}amazingco
    build:
      context: .
      dockerfile: AmazingCo/Dockerfile
    depends_on:
      - db

  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "The_Most_Secure_Password_In_The_World_v2"
      ACCEPT_EULA: "Y"